# Generated by Django 5.2.12 on 2026-04-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("codigo_bbv", models.CharField(max_length=30, unique=True)),
                ("sigla", models.CharField(blank=True, max_length=20, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("sitio_web", models.URLField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresa",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["codigo_bbv"], name="empresa_codigo__906ebd_idx"
                    ),
                    models.Index(fields=["activa"], name="empresa_activa_923fc5_idx"),
                    models.Index(fields=["sector"], name="empresa_sector_7e8944_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReporteFinanciero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gestion", models.PositiveIntegerField()),
                (
                    "trimestre",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Primer Trimestre"),
                            (2, "Segundo Trimestre"),
                            (3, "Tercer Trimestre"),
                            (4, "Cuarto Trimestre"),
                        ]
                    ),
                ),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
                ("fecha_descarga", models.DateTimeField(blank=True, null=True)),
                ("url_pdf", models.URLField(max_length=500)),
                (
                    "nombre_archivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ruta_archivo_local",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hash_archivo",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("tamano_archivo_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "estado_procesamiento",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("descargado", "Descargado"),
                            ("procesado", "Procesado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                ("datos_extraidos_json", models.JSONField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_financieros",
                        to="financials.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte financiero",
                "verbose_name_plural": "Reportes financieros",
                "db_table": "reporte_financiero",
                "ordering": ["-gestion", "-trimestre", "empresa__nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProcesoCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_proceso",
                    models.CharField(
                        choices=[
                            ("descarga", "Descarga"),
                            ("extraccion", "Extracción"),
                            ("limpieza", "Limpieza"),
                            ("calculo", "Cálculo"),
                            ("carga", "Carga completa"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_proceso", "En proceso"),
                            ("exitoso", "Exitoso"),
                            ("fallido", "Fallido"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("detalle", models.TextField(blank=True, null=True)),
                ("mensaje_error", models.TextField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos_carga",
                        to="financials.empresa",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procesos_carga",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso de carga",
                "verbose_name_plural": "Procesos de carga",
                "db_table": "proceso_carga",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="IndicadorFinanciero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingresos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "utilidad_neta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "activos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "pasivos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "patrimonio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "activo_corriente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "pasivo_corriente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "liquidez_corriente",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "endeudamiento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "margen_neto",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "crecimiento_ingresos_trimestral",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "crecimiento_ingresos_interanual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "crecimiento_utilidad_trimestral",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "crecimiento_utilidad_interanual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "score_financiero",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "clasificacion_riesgo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "recomendacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resumen_interpretativo", models.TextField(blank=True, null=True)),
                ("fecha_calculo", models.DateTimeField(auto_now=True)),
                (
                    "reporte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores",
                        to="financials.reportefinanciero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador financiero",
                "verbose_name_plural": "Indicadores financieros",
                "db_table": "indicador_financiero",
            },
        ),
        migrations.AddIndex(
            model_name="reportefinanciero",
            index=models.Index(
                fields=["empresa", "gestion", "trimestre"],
                name="reporte_fin_empresa_448b7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportefinanciero",
            index=models.Index(
                fields=["estado_procesamiento"], name="reporte_fin_estado__c5b887_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportefinanciero",
            index=models.Index(
                fields=["fecha_publicacion"], name="reporte_fin_fecha_p_a52223_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportefinanciero",
            constraint=models.UniqueConstraint(
                fields=("empresa", "gestion", "trimestre"),
                name="unique_reporte_por_empresa_gestion_trimestre",
            ),
        ),
        migrations.AddIndex(
            model_name="procesocarga",
            index=models.Index(
                fields=["tipo_proceso"], name="proceso_car_tipo_pr_a34dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procesocarga",
            index=models.Index(fields=["estado"], name="proceso_car_estado_b63070_idx"),
        ),
        migrations.AddIndex(
            model_name="procesocarga",
            index=models.Index(
                fields=["fecha_inicio"], name="proceso_car_fecha_i_3fa236_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicadorfinanciero",
            index=models.Index(
                fields=["score_financiero"], name="indicador_f_score_f_c0af6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indicadorfinanciero",
            index=models.Index(
                fields=["clasificacion_riesgo"], name="indicador_f_clasifi_1f8023_idx"
            ),
        ),
    ]
